on:
  pull_request_target:
    types:
      - opened
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Sorenon/gitter-action@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          users: |
            15383766
          
