on:
  pull_request_target:
    types:
      - opened
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Sorenon/gitter-action@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          users: |
            5092859230
            375483453
            735827592352
            73825972385
            3523542342
            234234235
          
