on:
  pull_request_target:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Sorenon/gitter-action@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
